name: maurivote
description: Application de vote électronique — République Islamique de Mauritanie
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Backend Supabase
  supabase_flutter: ^2.3.0
  flutter_dotenv: ^6.0.1

  # Auth & Sécurité
  local_auth: ^3.0.1
  flutter_secure_storage: ^10.0.0
  encrypt: ^5.0.3
  crypto: ^3.0.3
  secure_application: ^4.0.1

  # Navigation
  go_router: ^17.2.3

  # Riverpod — VERSION FIXÉE 2.x
  flutter_riverpod: ^3.3.1
  riverpod_annotation: ^4.0.2

  # UI & Animations
  lottie: ^3.0.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  fl_chart: ^1.2.0
  flutter_animate: ^4.3.0
  smooth_page_indicator: ^2.0.1
  pin_code_fields: ^9.3.0
  awesome_dialog: ^3.1.0
  qr_flutter: ^4.1.0
  data_table_2: ^2.5.9

  # Cartes
  url_launcher: ^6.2.3

  # Stockage local
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^7.1.1

  # Notifications
  firebase_core: ^4.7.0
  firebase_messaging: ^16.2.0
  firebase_crashlytics: ^5.2.0
  flutter_local_notifications: ^21.0.0

  # i18n
  intl: ^0.20.2

  # Formulaires
  flutter_form_builder: ^10.3.0+2
  form_builder_validators: ^11.3.0

  # Utilitaires
  share_plus: ^12.0.2
  shared_preferences: ^2.2.2
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8
  riverpod_generator: ^4.0.3

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env

